name: renovate-config-validator
on:
  workflow_call:
    inputs:
      ref:
        description: "checkout ref"
        required: false
        type: string
      validator_version:
        description: "version of renovate-config-validator. By default, the latest version is used."
        required: false
        type: string
      config_file_path:
        description: |
          Renovate Configuration file
          By default, the following files are validated.

          * .github/renovate.json
          * .github/renovate.json5
          * .gitlab/renovate.json
          * .gitlab/renovate.json5
          * .renovaterc.json
          * renovate.json
          * renovate.json5
          * .renovaterc
        required: false
        type: string
      runs-on:
        required: false
        type: string
        default: '"ubuntu-latest"'
        description: |
          JSON string for runs-on.
          e.g.
          runs-on: '"macos-latest"'
          runs-on: '["foo"]'
      node-version:
        required: false
        type: string

jobs:
  renovate-config-validator:
    timeout-minutes: 30
    runs-on: ${{fromJSON(inputs.runs-on)}}
    permissions:
      contents: read # For checkout private repository
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{inputs.ref}}
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        if: inputs.node-version != ''
        with:
          node-version: ${{inputs.node-version}}
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@36a15b83e37bf3221dc9c02ff5ffdaefb51ca1cf # v1.1.0
        with:
          validator_version: ${{inputs.validator_version}}
          config_file_path: ${{inputs.config_file_path}}
