name: renovate-config-validator
on:
  workflow_call:
    inputs:
      validator_version:
        description: "version of renovate-config-validator. By default, the latest version is used."
        required: false
        type: string
      config_file_path:
        description: |
          Renovate Configuration file
          By default, the following files are validated.

          * .github/renovate.json
          * .github/renovate.json5
          * .gitlab/renovate.json
          * .gitlab/renovate.json5
          * .renovaterc.json
          * renovate.json
          * renovate.json5
          * .renovaterc
        required: false
        type: string
      runs-on:
        required: false
        type: string
        default: '"ubuntu-latest"'
        description: |
          JSON string for runs-on.
          e.g.
          runs-on: '"macos-latest"'
          runs-on: '["foo"]'
      node-version:
        required: false
        type: string

permissions: {}

jobs:
  renovate-config-validator:
    runs-on: ${{fromJSON(inputs.runs-on)}}
    permissions:
      contents: read # For checkout private repository
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        if: inputs.node-version != ''
        with:
          node-version: ${{inputs.node-version}}
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b7cd2b598bb51d071a2474e98f55cc25f91abec1 # v0.1.3
        with:
          validator_version: ${{inputs.validator_version}}
          config_file_path: ${{inputs.config_file_path}}
